-- 방법1
# SELECT AI.NAME, AI.DATETIME
# FROM ANIMAL_INS AI
# LEFT JOIN ANIMAL_OUTS AO
# ON AI.ANIMAL_ID = AO.ANIMAL_ID
# WHERE AO.DATETIME IS NULL
# ORDER BY AI.DATETIME
# LIMIT 3;

-- 방법2
# SELECT NAME, DATETIME FROM ANIMAL_INS A
# WHERE NOT EXISTS (SELECT ANIMAL_ID FROM ANIMAL_OUTS B WHERE A.ANIMAL_ID = B.ANIMAL_ID)
# ORDER BY DATETIME
# LIMIT 3;

-- 방법3
SELECT NAME, DATETIME
FROM ANIMAL_INS
WHERE ANIMAL_ID NOT IN (SELECT ANIMAL_ID FROM ANIMAL_OUTS)
ORDER BY DATETIME
LIMIT 3;