-- 코드를 입력하세요
SELECT FP.PRODUCT_ID, FP.PRODUCT_NAME, SUM(FP.PRICE*FO.AMOUNT) AS TOTAL_SALES
FROM FOOD_PRODUCT FP
JOIN FOOD_ORDER FO
ON FP.PRODUCT_ID = FO.PRODUCT_ID
WHERE TO_CHAR(PRODUCE_DATE, 'MM') = '05'
GROUP BY FP.PRODUCT_ID, FP.PRODUCT_NAME
ORDER BY 3 DESC, 1;